#
#
#

runs:
  using: "composite"
  steps:
    - name: 'Install Python 3.10'
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: 'Install pip, venv & dependencies'
      shell: bash
      run: |
        function execute() { echo -e "\033[0;34m$*\033[0m"; "$@"; }

        execute python -m venv venv
        execute source venv/bin/activate
        execute python -m pip install --upgrade pip
        execute python -m pip install wheel
        execute python -m pip install -r requirements.txt
