#
#
#

runs:
  using: "composite"
  steps:
    - name: 'Execute Python Build'
      shell: bash
      run: |
        function execute() { echo -e "\033[0;34m$*\033[0m"; "$@"; }

        execute source venv/bin/activate
        execute make test-python
        execute make clean
        execute make build
