name: 'Test mpvQC'

on:
  push:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-22.04
    name: 'Run Python & Qml Tests'
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Python 3.10'
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: 'Install pip'
        run: |
          python -m pip install --upgrade pip
      - name: 'Install Qt 6.3.0'
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.3.0'
      - name: 'Update packages'
        run: |
          sudo apt update -y && sudo apt upgrade -y
      - name: 'Install dependencies'
        run: |
          sudo apt install -y make libmpv1 patchelf libopengl0
      - name: 'Create virtual environment'
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install wheel
          python -m pip install -r requirements.txt
          python -m pip install pytest-tap
      - name: 'Test'
        run: |
          export QT_QPA_PLATFORM=offscreen
          source venv/bin/activate

          make prepare-test
          echo "# Python Test Results" > $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          pytest --tap-stream \
            | grep -E '^(ok|not ok|#)' \
            | sed -e 's/^ok/- ✅/' -e 's/^not ok\(.*\)/- ❌\1\n/' -e 's/#/     /' \
            | tee -a $GITHUB_STEP_SUMMARY
          
          make clean
          echo "# Qml Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          qmltestrunner -tap \
            | grep -E '^(ok|not ok|  )' \
            | sed -e 's/^ok/- ✅/' -e 's/^not ok\(.*\)/- ❌\1\n/' -e 's/  /       /' \
            | grep -Ev '  (---)'\
            | grep -Ev '  (\.\.\.)'\
            | tee -a $GITHUB_STEP_SUMMARY
