name: Test

on:
  push:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.4"

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Update packages
        run: |
          sudo apt update -y && sudo apt upgrade -y

      - name: Install dependencies
        # Currently we need to install 'qttools5-dev-tools' to use the 'lrelease' command
        run: |
          sudo apt install -y make libmpv1 qttools5-dev-tools patchelf libopengl0

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install -r requirements.txt

      - name: Test application
        run: |
          source venv/bin/activate
          make test
