name: 'Test mpvQC'

on:
  push:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-22.04
    name: 'Run Python & Qml Tests'
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Python 3.10'
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: 'Install Qt 6.3.0'
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.3.0'
      - name: 'Install pip'
        run: |
          python -m pip install --upgrade pip
      - name: 'Update packages'
        run: |
          sudo apt update -y && sudo apt upgrade -y
      - name: 'Install dependencies'
        run: |
          sudo apt install -y make libmpv1 patchelf libopengl0
      - name: 'Create virtual environment'
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install -r requirements.txt
      - name: 'Test application'
        run: |
          export QT_QPA_PLATFORM=offscreen
          source venv/bin/activate
          make test
